@host = http://localhost:5260

POST {{host}}/anagram
Content-Type: application/json

{"word":  "tárol"}

###

POST {{host}}/anagram
Content-Type: application/json

{"word":  "rrzáá"}
        
###

POST {{host}}/anagram
Content-Type: application/json

{"word":  "xxxxx"}

###

POST {{host}}/anagram
Content-Type: application/json

{"word":  "xx"}

###

POST {{host}}/anagram
Content-Type: application/json

{"word":  "xxxxxx"}
