POST http://localhost:5260/anagram
Content-Type: application/json

{"word":  "tárol"}

###

POST http://localhost:5260/anagram
Content-Type: application/json

{"word":  "rrzáá"}
        
###

POST http://localhost:5260/anagram
Content-Type: application/json

{"word":  "xxxxx"}

###

POST http://localhost:5260/anagram
Content-Type: application/json

{"word":  "xx"}

###

POST http://localhost:5260/anagram
Content-Type: application/json

{"word":  "xxxxxx"}
